<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilioNo_ExtraInvoice-1_EditText</name>
   <tag></tag>
   <elementGuidId>d8c8c045-0e5d-4f42-91a4-6844b2cc5e7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//android.widget.LinearLayout[1]/android.widget.LinearLayout/
android.widget.ScrollView/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView[1]/
android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.EditText
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//android.widget.LinearLayout[1]/android.widget.LinearLayout/
android.widget.ScrollView/android.widget.LinearLayout/androidx.recyclerview.widget.RecyclerView[1]/
android.widget.LinearLayout[2]/android.widget.LinearLayout[1]/android.widget.EditText
</value>
   </webElementProperties>
</WebElementEntity>
