<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SNum_Indexing</name>
   <tag></tag>
   <elementGuidId>058488d6-8e45-4bd5-929a-c83c3cd18489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//*[@resource-id='${GlobalVariable.Package}:id/proposalQty'])[${GlobalVariable.index}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//*[@resource-id='${GlobalVariable.Package}:id/proposalQty'])[${GlobalVariable.index}]</value>
   </webElementProperties>
</WebElementEntity>
